# fields.py

CLIENT_REGISTRATION_FIELDS = [
    "ClientCode",                      # 1
    "PrimaryHolderFirstName",          # 2
    "PrimaryHolderMiddleName",         # 3
    "PrimaryHolderLastName",           # 4
    "TaxStatus",                       # 5
    "Gender",                          # 6
    "PrimaryHolderDOB",               # 7
    "OccupationCode",                 # 8
    "HoldingNature",                  # 9
    "SecondHolderFirstName",          # 10
    "SecondHolderMiddleName",         # 11
    "SecondHolderLastName",           # 12
    "ThirdHolderFirstName",           # 13
    "ThirdHolderMiddleName",          # 14
    "ThirdHolderLastName",            # 15
    "SecondHolderDOB",               # 16
    "ThirdHolderDOB",                # 17
    "GuardianFirstName",              # 18
    "GuardianMiddleName",             # 19
    "GuardianLastName",               # 20
    "GuardianDOB",                    # 21
    "PrimaryHolderPANExempt",         # 22
    "SecondHolderPANExempt",          # 23
    "ThirdHolderPANExempt",           # 24
    "GuardianPANExempt",              # 25
    "PrimaryHolderPAN",               # 26
    "SecondHolderPAN",                # 27
    "ThirdHolderPAN",                 # 28
    "GuardianPAN",                    # 29
    "PrimaryHolderExemptCategory",     # 30
    "SecondHolderExemptCategory",      # 31
    "ThirdHolderExemptCategory",       # 32
    "GuardianExemptCategory",          # 33
    "ClientType",                     # 34
    "PMS",                           # 35
    "DefaultDP",                      # 36
    "CDSLDPID",                      # 37
    "CDSLCLTID",                     # 38
    "CMBPId",                        # 39
    "NSDLDPID",                      # 40
    "NSDLCLTID",                     # 41
    "AccountType1",                   # 42
    "AccountNo1",                     # 43
    "MICRNo1",                       # 44
    "IFSCCode1",                     # 45
    "DefaultBankFlag1",              # 46
    "AccountType2",                  # 47
    "AccountNo2",                    # 48
    "MICRNo2",                      # 49
    "IFSCCode2",                    # 50
    "DefaultBankFlag2",             # 51
    "AccountType3",                 # 52
    "AccountNo3",                   # 53
    "MICRNo3",                     # 54
    "IFSCCode3",                   # 55
    "DefaultBankFlag3",            # 56
    "AccountType4",                # 57
    "AccountNo4",                  # 58
    "MICRNo4",                    # 59
    "IFSCCode4",                  # 60
    "DefaultBankFlag4",           # 61
    "AccountType5",               # 62
    "AccountNo5",                 # 63
    "MICRNo5",                   # 64
    "IFSCCode5",                 # 65
    "DefaultBankFlag5",          # 66
    "ChequeName",                # 67
    "DivPayMode",               # 68
    "Address1",                 # 69
    "Address2",                 # 70
    "Address3",                 # 71
    "City",                     # 72
    "State",                    # 73
    "Pincode",                  # 74
    "Country",                  # 75
    "ResiPhone",                # 76
    "ResiFax",                  # 77
    "OfficePhone",              # 78
    "OfficeFax",                # 79
    "Email",                    # 80
    "CommunicationMode",        # 81
    "ForeignAddress1",          # 82
    "ForeignAddress2",          # 83
    "ForeignAddress3",          # 84
    "ForeignAddressCity",       # 85
    "ForeignAddressPincode",    # 86
    "ForeignAddressState",      # 87
    "ForeignAddressCountry",    # 88
    "ForeignAddressResiPhone",  # 89
    "ForeignAddressFax",        # 90
    "ForeignAddressOffPhone",   # 91
    "ForeignAddressOffFax",     # 92
    "IndianMobileNo",           # 93
    "Nominee1Name",             # 94
    "Nominee1Relationship",     # 95
    "Nominee1Percentage",       # 96
    "Nominee1MinorFlag",        # 97
    "Nominee1DOB",             # 98
    "Nominee1Guardian",        # 99
    "Nominee2Name",            # 100
    "Nominee2Relationship",    # 101
    "Nominee2Percentage",      # 102
    "Nominee2DOB",            # 103
    "Nominee2MinorFlag",       # 104
    "Nominee2Guardian",       # 105
    "Nominee3Name",           # 106
    "Nominee3Relationship",   # 107
    "Nominee3Percentage",     # 108
    "Nominee3DOB",           # 109
    "Nominee3MinorFlag",      # 110
    "Nominee3Guardian",      # 111
    "PrimaryHolderKYCType",      # 112
    "PrimaryHolderCKYCNumber",   # 113
    "SecondHolderKYCType",       # 114
    "SecondHolderCKYCNumber",    # 115
    "ThirdHolderKYCType",        # 116
    "ThirdHolderCKYCNumber",     # 117
    "GuardianKYCType",           # 118
    "GuardianCKYCNumber",        # 119
    "PrimaryHolderKRAExemptRefNo",    # 120
    "SecondHolderKRAExemptRefNo",     # 121
    "ThirdHolderKRAExemptRefNo",      # 122
    "GuardianKRAExemptRefNo",         # 123
    "AadhaarUpdated",            # 124
    "MapinId",                   # 125
    "PaperlessFlag",            # 126
    "LEINo",                    # 127
    "LEIValidity",              # 128
    "MobileDeclarationFlag",    # 129
    "EmailDeclarationFlag",     # 130
    "Filler3"                   # 131
]